services:
  fastapi:
    build: .
    container_name: fastapi_book_project_afanyu
    restart: always
    networks:
      - app_network
    expose:
      - "8000"  # Expose internal port to Docker network
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8213:80"  # Host port 8213 -> Container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
